- src/originalBudgetTrackingApp/bankScraper.ts
- src/originalBudgetTrackingApp/configManager/configManager.ts
- src/originalBudgetTrackingApp/index.ts
> Fix Scraping process

- src/components/App/Importers.vue
- src/components/App/Importers/Importer.vue
> Small old UI fix

- package.json
- src/components/app/ConfigEditor.vue
- src/components/app/Importers.vue
- src/components/app/exporters/Exporter.vue
- src/components/app/importers/AddImporter.vue
- src/components/app/importers/Importer.vue
- src/main.ts
- src/store/index.ts
- src/store/modules/config.ts
- yarn.lock
I will take this into my work on Exporters components
> Direct vuex

- src/components/app/ConfigEditor.vue
- src/components/app/Exporters.vue
- src/components/app/MainContent.vue
- src/components/app/exporters/ExpansionPanel.vue
- src/components/app/exporters/JsonExporter.vue
- src/components/app/exporters/YnabAccountMappingTable.vue
- src/components/app/exporters/YnabExporter.vue
- src/components/shared/log/LogViewer.vue
- src/store/modules/config.ts
I wrongly used `Vue.extend`. Using `defineComponent` is better and solving the issue with the typed `props`.
> change Vue.extend to defineComponent

- .github/workflows/release.yml
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
> set env into file

- .vscode/extensions.json
- src/ui/components/app/exporters/CsvExporter.vue
- src/ui/components/app/exporters/JsonExporter.vue
- src/ui/components/app/exporters/YnabExporter.vue
- src/ui/components/app/exporters/exportersCommon.ts
- src/ui/components/app/exporters/googleSheets/SpreadsheetExporter.vue
> fix #166 Exporter is ready even it invalid

- globals.js
- package.json
- src/analytics.ts
- src/backend/index.ts
- src/types/global.d.ts
- src/ui/components/App.vue
- src/ui/components/app/MainContent.vue
- yarn.lock
Closes #145 
Added analytics that are sent to segment. 
We have full control over the data that is sent so we can make sure no personal or sensitive information is sent.
What is being tracked:
1. "Page views" - how many times the app was loaded
2. Scraping events - just the name of the vendor, name of event and if is error or not.
We don't identify the user himself. Instead we use a hash of the machine id as the identifier so we don't event have the actual machine id, just the hash.
> Anonymous analytics tracking

- src/backend/configManager/configManager.ts
- src/backend/consts.ts
- src/backend/import/downloadChromium.ts
- src/backend/import/importTransactions.ts
- src/backend/index.ts
- src/manual/setupHelpers.ts
- src/ui/components/app/MainContent.vue
- src/ui/store/modules/config.ts
- src/ui/store/plugins/persisted-config.ts
Fix #173 
Injecting the config/configPath and setting the path as const in a shared file.
> Save config in UserData path

- globals.js
- package.json
- public/index.html
- src/backend/configManager/encryption/keytar.ts
- src/main.ts
- src/types/global.d.ts
- src/ui/components/App.vue
- test/e2e/specs/launch.spec.ts
- vue.config.js
Use repo name and URL from package.config #103
> add global app name and repo #103

- .github/dependabot.yml
- package.json
- yarn.lock
Close #199 #196 #195 #165 #163 #158
It is working, I tested it locally on Windows.
> All dependabot updates

- src/ui/components/shared/log/LogViewer.vue
> fix lint after merge

- src/backend/export/outputVendors/ynab/ynab.ts
just enter the category manually. no need to stop the whole process.
> no category exists when exporting to ynab

- .github/workflows/release.yml
During the **build**, we are using *Webpack* to replace all known variables with their known value. https://v4.webpack.js.org/plugins/define-plugin/
You can see the code here:
https://github.com/brafdlog/hiuvi/blob/734aafcff19fb200c7ed0e0c4a75874f5405be61/vue.config.js#L5-L8
> Build with Segment Key

- .github/workflows/release.yml
- package.json
- src/logging/sentry.ts
- yarn.lock
The user reports didn't showed in Sentry. After trying things it seems we have to enable JS
> send user report

- src/backend/export/outputVendors/csv/csv.ts
Hi first time here... :)
My suggestion how to solve issue #265 
https://github.com/brafdlog/caspion/issues/265
Based on solution:
https://stackoverflow.com/questions/17879198/adding-utf-8-bom-to-string-blob/27975629#27975629
tested on Windows 10 machine and Excel 2016 successfully
Thanks!
> Adding UTF-8 BOM to csv export - Issue #265

- package.json
- yarn.lock
https://github.com/vuetifyjs/vuetify/issues/13694
> build junk output workaround

- package.json
- yarn.lock
https://github.com/eshaham/israeli-bank-scrapers/compare/v1.5.0...v1.5.3
> Upgrade israel scrapers to 1.5.3

- package.json
- yarn.lock
> Update Israeli bank scrapers

- package.json
- yarn.lock
https://github.com/eshaham/israeli-bank-scrapers/compare/v1.11.0...v1.11.1﻿
> upgrade israli-bank-scraper

- package.json
- yarn.lock
https://github.com/eshaham/israeli-bank-scrapers/compare/v1.12.1...v1.13.0
> upgrade israeli-bank-scrapers to 1.12.0

- package.json
- yarn.lock
https://github.com/eshaham/israeli-bank-scrapers/compare/v1.13.0...v1.13.1
> upgrade israeli-bank-scrapers to 1.13.1

- package.json
- yarn.lock
https://github.com/eshaham/israeli-bank-scrapers/compare/v1.13.5...v1.14.3
> upgrade israeli-bank-scrapers to v1.14.1

- src/backend/export/outputVendors/googleSheets/googleSheets.ts
The purpose is to add the 6 fields that exist in the csv export file (csv.ts), but are missing from this Google Sheets export. 
Please note that I used to be a programmer, but in C++, not Java or anything after it.  
I have no idea how to test the changes that I propose ... , so this is NOT TESTED.
> Add missing fields to GoogleSheets exporter

- globals.js
- src/types/global.d.ts
- src/ui/components/App.vue
> Add link to discord

- package.json
- yarn.lock
https://github.com/eshaham/israeli-bank-scrapers/compare/v2.0.0...v2.1.0
> Upgrade: israeli-bank-scrapers to v2.1.0

- package.json
- release.config.js
- yarn.lock
https://github.com/eshaham/israeli-bank-scrapers/compare/v2.1.0...v2.1.1
Fixes #375
> Deps: upgrade israeli-bank-scrapers to 2.1.1

- package.json
- yarn.lock
https://github.com/eshaham/israeli-bank-scrapers/compare/v2.1.1...v2.2.0
> Deps: upgrade israeli-bank-scrapers to 2.2.0

- ui-react/src/components/accounts/Account.tsx
- ui-react/src/components/accounts/Importers.tsx
- ui-react/src/components/exporters/Exporters.tsx
> Fix: Show logs icon even when scraping ends

- package.json
- yarn.lock
https://github.com/eshaham/israeli-bank-scrapers/compare/v3.0.0...v3.1.2
> Deps: upgrade israeli-bank-scrapers to 3.1.2

- src/backend/commonTypes.ts
- src/backend/eventEmitters/EventEmitter.ts
- src/backend/export/exportTransactions.ts
- src/backend/export/outputVendors/csv/csv.ts
- src/backend/export/outputVendors/googleSheets/googleSheets.ts
- src/backend/export/outputVendors/json/json.ts
- src/backend/export/outputVendors/ynab/ynab.ts
- ui-react/src/Store.tsx
- ui-react/src/components/accounts/Account.module.css
- ui-react/src/components/accounts/Account.tsx
- ui-react/src/types.tsx
Code is not super elegant, but does the job.
> New: Show a badge with number of created txns in exporter

- ui-react/src/components/Body.module.css
- ui-react/src/components/Body.tsx
> Fix: for overlapping controls

- .github/workflows/pr-title.yml
See more here: https://dev.to/baruchiro/how-to-setup-auto-semantic-release-4fd8
> Warn if PR title will not trigger a release

- ui-react/src/components/accounts/EditImporter.tsx
> Fix: Re add missing import

- package.json
- yarn.lock
https://github.com/eshaham/israeli-bank-scrapers/compare/v3.1.2...v3.3.0
> Deps: upgrade israeli-bank-scrapers to v3.3.0

- src/handlers/index.ts
- src/handlers/logsHandlers.ts
- ui-react/src/components/topBar/LogsCanvas.tsx
- ui-react/src/components/topBar/ReportProblemModal.tsx
- ui-react/src/eventsBridge.tsx
The new features:
* send a problem report to _Sentry_ as well
* see logs folder
* attached logs and send them to github\sentry
> New: Add report to Sentry & send attached logs

- ui-react/src/components/accounts/EditImporter.tsx
Call `checkFieldsValidity` function when `onActiveChanged` occures
+ some code refactor
> Fix: Importer button save disabled

- src/backend/commonTypes.ts
- src/backend/configManager/defaultConfig.ts
- src/backend/import/bankScraper.ts
- src/backend/import/importTransactions.ts
- ui-react/src/Store.tsx
- ui-react/src/components/GeneralSettings.tsx
- ui-react/src/types.tsx
> New: make the scraping timeout configurable

- package.json
- yarn.lock
> Chore: upgrade MacOS build to include Python

- package.json
- yarn.lock
https://github.com/eshaham/israeli-bank-scrapers/compare/v3.3.0...v3.4.0
> Deps: upgrade israeli-bank-scrapers to 3.4.0

- .eslintrc.js
- src/handlers/index.ts
- ui-react/package.json
- ui-react/src/Store.tsx
- ui-react/src/components/App.tsx
- ui-react/src/components/Body.tsx
- ui-react/src/components/CheckForUpdates.module.css
- ui-react/src/components/CheckForUpdates.tsx
- ui-react/src/components/topBar/LogsCanvas.tsx
- ui-react/src/components/topBar/ReportProblemModal.tsx
- ui-react/src/components/topBar/TopBar.tsx
- ui-react/src/eventsBridge.tsx
- ui-react/src/types.tsx
> New: Implement check for updates

- ui-react/src/components/CheckForUpdates.tsx
- ui-react/src/eventsBridge.tsx
> Fix: Add "quit and install" button

- package.json
- yarn.lock
https://github.com/eshaham/israeli-bank-scrapers/compare/v3.4.0...v3.6.0
> Deps: upgrade israeli-bank-scrapers to 3.6.0

- .github/workflows/nuxt.yml
- nuxt/yarn.lock
- ui-react/yarn.lock
- yarn.lock
- Bump json5 from 1.0.1 to 1.0.2 in /ui-react
- Bump ua-parser-js from 0.7.28 to 0.7.35 in /nuxt
- Bump json5 from 1.0.1 to 1.0.2 in /nuxt
- Bump ua-parser-js from 0.7.28 to 0.7.35
> Deps: dependabot upgrades

- package.json
- yarn.lock
https://github.com/eshaham/israeli-bank-scrapers/compare/v3.9.0...v3.10.1
> Deps: upgrade israeli-bank-scrapers to v3.10.1

- package.json
- yarn.lock
https://github.com/eshaham/israeli-bank-scrapers/compare/v3.10.1...v3.10.2
> Deps: upgrade israeli-bank-scrapers to 3.10.2

- src/handlers/index.ts
> Fix: register a second handler (fixes #478)

- package.json
- yarn.lock
https://github.com/eshaham/israeli-bank-scrapers/compare/v3.10.2...v3.10.3
> Deps: upgrade israeli-bank-scrapers to 3.10.3

- package.json
- src/backend/transactions/transactions.ts
- test/unit/specs/transactions.test.ts
> Fix: remove another special character to the hash

- src/backend/import/importTransactions.ts
> Fix: disable category enrichment (fixes #518)

- ui-react/src/components/Body.module.css
- ui-react/src/components/Body.tsx
- ui-react/src/components/GeneralSettings.tsx
- ui-react/src/components/accounts/Account.module.css
- ui-react/src/components/accounts/Account.tsx
- ui-react/src/components/accounts/EditImporter.tsx
- ui-react/src/components/topBar/ReportProblemModal.tsx
Hi, 
I added cursor pointer fot the buttons and auto focus in the forms in the first screen of the app.
> New: cursor and autoFocus

- packages/main/src/backend/import/downloadChromium.ts
This fixes issue: https://github.com/brafdlog/caspion/issues/599
> Fix: bump chromium revision to 1364960

- .github/workflows/stale.yml
See:
https://github.com/actions/stale?tab=readme-ov-file#ascending
https://github.com/actions/stale?tab=readme-ov-file#operations-per-run
> add ascending because of the rate limit
