brafdlog/caspion

src/originalBudgetTrackingApp/bankScraper.ts
We have to be aware to keep the credentials safe as possible.
We can't use the credentials in any flow except from decryption to `israeli-bank-scrapers` and from input to encryption.
In the future we can consider to write a custom query in Semmle (or Checkmarx, I hope! :-) ) to find these paths.
=> never print password

.eslintrc.js, src/components/App/ConfigEditor.vue, src/components/App/Importers/Importer.vue, src/components/App/MainContent.vue, src/originalBudgetTrackingApp/configManager/configManager.ts, src/originalBudgetTrackingApp/configManager/defaultConfig.ts, src/originalBudgetTrackingApp/index.ts, src/store/modules/Config.ts, src/types/vuetify.ts
In forms, we have two ways- make the form reactive so any change will **immediately update** the state and the config, and the other way- **clone** the editable object, make the changes and update the config **only when the user press "Send"**.
I prefer the second way (but I know nowadays the first way come to be common).
In the second way, in Vue, we have two ways:
- Split the two-way binding by setting the value of the field with the **original value**, but listen to the `change` event to update the **local component state**, and send the updated state when the user submits.
- Clone **the whole object** (by `JSON.parse(JSON.stringify` for example) and **bind** it to the UI.
In this form I selected the second way.
=> Edit global config in UI

src/originalBudgetTrackingApp/export/outputVendors/googleSheets/googleSheets.ts, src/originalBudgetTrackingApp/export/outputVendors/googleSheets/googleSheetsInternalAPI.ts
- Fix hash column (the current code is fragile because it assumes the which column is the hash column. Will think of a way to make this safer)
- Throw clear error if no sheet with the expected name exists
=> Sheets fixes

globals.js, package.json, src/types/global.d.ts, src/ui/components/app/ReportProblemDialog.vue, src/ui/plugins/logger.ts
Now really fix #170 
Fixing these:
Example report:
----
The bug details
Another line
```
[2020-12-29 21:55:38.207] [info] The renderer process got the logger
[2020-12-29 21:55:51.970] [info] Open bug report url with title: seservr
[2020-12-29 21:57:31.526] [info] The renderer process got the logger
[2020-12-29 21:59:19.133] [info] The renderer process got the logger
[2020-12-29 22:01:11.334] [info] The renderer process got the logger
[2020-12-29 22:02:54.733] [info] The renderer process got the logger
[2020-12-29 22:11:38.177] [info] Welcome to budget-tracking log
[2020-12-29 22:11:38.212] [info] Version: 0.1.3-beta
[2020-12-29 22:11:56.238] [info] The renderer process got the logger
```
- Source Version: `unknown`
- OS: `win32x64`
- OS Version: `10.0.20270`
=> Fix ReportProblem

.github/dependabot.yml, package.json, src/ui/components/app/exporters/YnabAccountMappingTable.vue, src/ui/components/app/exporters/googleSheets/SheetsCombobox.vue, src/ui/components/shared/log/AccountCard.vue, src/ui/components/shared/log/AccountCardStatusIndicator.vue, yarn.lock
- update dependabot configuration (close #209)
- Bump sass-loader from 8.0.2 to 11.0.1 (close #206)
- Bump eslint-plugin-standard from 4.1.0 to 5.0.0 (close #207)
- Bump eslint-plugin-vue from 6.2.2 to 7.7.0 (close #210)
- yarn lint:fix
- ignore typescript and sass-loader v11 (close #208)
=> All dependabot updates

src/backend/eventEmitters/EventEmitter.ts, src/backend/index.ts, src/ui/components/app/MainContent.vue, src/ui/components/app/accountsState.ts, src/ui/components/shared/log/LogViewer.vue
=> Show chrome downloading progress

.eslintrc.js, src/backend/import/bankScraper.ts
=> Missing credentials for scraper. CompanyId: hapoalim 

package.json, yarn.lock
Package published automatically by Github Actions: https://github.com/eshaham/israeli-bank-scrapers/runs/2739732884
Diff: https://github.com/eshaham/israeli-bank-scrapers/compare/v1.1.1...v1.2.0
=> upgrade israli-bank-scrapers to 1.2.0

.github/workflows/chainalert.yml
[ChainAlert](https://github.com/Checkmarx/chainalert-github-action) is a new product from Checkmarx to alert if we have a volnurability in the supply chain.﻿
=> Add Chain Alert

nuxt/yarn.lock
- Bump minimist from 1.2.5 to 1.2.6 in /nuxt
- Bump async from 2.6.3 to 2.6.4 in /nuxt
- Bump shell-quote from 1.7.2 to 1.7.3 in /nuxt
=> Nuxt upgrades from dependabot

package.json, yarn.lock
- Bump minimist from 1.2.5 to 1.2.6
- Bump plist from 3.0.2 to 3.0.5
- Bump eventsource from 1.1.0 to 1.1.1
- Bump semver-regex from 3.1.2 to 3.1.4
- Bump shell-quote from 1.7.2 to 1.7.3
- Bump moment from 2.29.1 to 2.29.3
=> Upgrades from dependabot

package.json, yarn.lock
https://github.com/eshaham/israeli-bank-scrapers/compare/v1.14.3...v2.0.0
- **[2.0.0](https://github.com/eshaham/israeli-bank-scrapers/compare/v1.15.1...v2.0.0) (2022-08-30):** changing default time-zone to Asia/Jerusalem shouldn't affect people scrapping usually from Israel but might affect people that always scrape outside of Israel.
- **[2.0.0](https://github.com/eshaham/israeli-bank-scrapers/compare/v1.15.1...v2.0.0) (2022-08-30):** use timezone Asia/Jerusalem by default (https://github.com/eshaham/israeli-bank-scrapers/issues/715) ([b369559](https://github.com/eshaham/israeli-bank-scrapers/commit/b369559c92c001cca9ce14c7ab75fde5629a895c))
- **[1.15.0](https://github.com/eshaham/israeli-bank-scrapers/compare/v1.14.4...v1.15.0) (2022-08-25):** add option to set the default timeout on …
=> upgrade israeli-bank-scrapers

nuxt/components/DownloadButton.vue, nuxt/test/__snapshots__/HeroContent.spec.js.snap, vue.config.js
- remove version from artifact name: We need the downloaded file from a release to be in a constant name (currently it includes the version)
- keep the same download link with 'latest'
- remove "more downloads" button
We will have to check the artifact filenames because they have different format for each file type.
This PR will not trigger a relase.
=> Keep the download URL consistent

nuxt/yarn.lock, ui-react/yarn.lock, yarn.lock
- Bump loader-utils from 1.4.0 to 1.4.2 in /nuxt (#395)
- Bump decode-uri-component from 0.2.0 to 0.2.2 (#407)
- Bump decode-uri-component from 0.2.0 to 0.2.2 in /ui-react (#409)
- Bump decode-uri-component from 0.2.0 to 0.2.2 in /nuxt (#410)
- Bump qs from 6.5.2 to 6.5.3 (#413)
- Bump qs from 6.5.2 to 6.5.3 in /nuxt (#414)
- Bump express from 4.17.1 to 4.18.2 (#415)
=> Upgrade: Dependabot alerts

package.json, src/ui/components/app/exporters/googleSheets/electronGoogleOAuth2Connector.ts, yarn.lock
The original @getstation/electron-google-oauth2 is not support Electron v14:
https://github.com/getstation/electron-google-oauth2/issues/42
And the author is not responding:
https://github.com/getstation/electron-google-oauth2/pull/43
I forked this project and published a new version.
=> Chore: use electron-google-oauth2 from @baruchiro

ui-react/yarn.lock, yarn.lock
- Bump jszip from 3.6.0 to 3.10.1
- Bump http-cache-semantics from 4.1.0 to 4.1.1
- Bump http-cache-semantics from 4.1.0 to 4.1.1 in /ui-react
- Bump minimist from 1.2.5 to 1.2.8
=> Deps: dependabot updates

src/backend/export/outputVendors/googleSheets/googleSheets.ts
This is a fix for https://github.com/brafdlog/caspion/issues/476 ("google spreadsheet dates inconsistent cell format")
The fix is to  use the format of `YYYY-MM-DD` which has no ambiguity and Google Sheets will automatically detect it as a date field.
I did not see any unit-testing in this project so added no tests. If I am missing the tests, I will add.
=> Fix: Ensure consistent dates for G-Sheets export

nuxt/yarn.lock, ui-react/yarn.lock, yarn.lock
- Upgrade: Bump follow-redirects from 1.15.4 to 1.15.6 in /ui-react
- Upgrade: Bump follow-redirects from 1.15.4 to 1.15.6 in /nuxt
- Upgrade: (deps): Bump follow-redirects from 1.15.4 to 1.15.6
=> Upgrade: Bump follow-redirects

nuxt/package.json, nuxt/yarn.lock, ui-react/yarn.lock, yarn.lock
- **Upgrade: Bump tar from 6.1.11 to 6.2.1 in /nuxt**
- **Upgrade: (deps): Bump tar from 6.1.11 to 6.2.1**
- **Upgrade: Bump tar from 6.1.13 to 6.2.1 in /ui-react**
- **Upgrade: Bump gh-pages from 2.2.0 to 5.0.0 in /nuxt**
=> Upgrade: Bump tar from 6.1.11 to 6.2.1

package.json, packages/main/src/backend/configManager/configManager.ts, packages/main/src/backend/export/exportTransactions.ts, packages/main/src/backend/export/outputVendors/csv/csv.ts, packages/main/src/backend/export/outputVendors/json/json.ts, packages/main/src/backend/export/outputVendors/ynab/ynab.test.ts, packages/main/src/backend/export/outputVendors/ynab/ynab.ts, packages/main/src/backend/import/downloadChromium.ts, packages/main/src/backend/import/importTransactions.ts, packages/main/src/backend/index.ts, packages/main/src/logging/logger.ts, packages/renderer/src/components/App.tsx, packages/renderer/src/index.tsx, packages/renderer/src/logging/logger.ts, yarn.lock
This pull request refactors the logging statements in the codebase to use the logger instead of console.log. This improves the consistency and maintainability of the logging system.
The following commits are included in this pull request:
- license package.json
- enable logger
- Refactor logging statements to use logger instead of console.log
=> Fix: logging and empty config

package.json, yarn.lock
This fixes: https://github.com/brafdlog/caspion/issues/573
=> Chore: vulnerabilities in underscore and ws

.github/workflows/stale.yml
The configuration must be on the default branch and the values will:
1. Add a label "Stale" on issues and pull requests after 60 days of inactivity and comment on them
2. Close the stale issues and pull requests after 14 days of inactivity
3. If an update/comment occur on stale issues or pull requests, the stale label will be removed and the timer will restart
=> Build: Add stale workflow

packages/main/src/backend/commonTypes.ts, packages/main/src/backend/eventEmitters/EventEmitter.ts, packages/main/src/backend/index.ts, packages/main/src/handlers/index.ts, packages/preload/src/eventsBridge.ts, packages/preload/src/index.ts, packages/renderer/src/components/Body.tsx, packages/renderer/src/components/GeneralSettings.tsx, packages/renderer/src/store/ConfigStore.tsx, packages/renderer/src/types.tsx
הוספתי אפשרות בהגדרות להגיד שרוצים שירוץ אוטומטית כל כמה שעות
זה נראה ככה:
כשלוחצים על הפעל זה מאתחל את הטיימר של ההרצה האוטומטית.
=> New: Support automatic scraping periodically
